
- name: CREATE volumes path
  ansible.builtin.file:
    path: "/root/nifi/volumes"
    state: directory
    recurse: yes
    force: yes

- name: COPY
  copy:
    src: "{{ role_path }}/files"
    dest: "/root/nifi"

- name: BUILD
  community.docker.docker_image:
    name: nifi-pbl:1.0.0
    source: build
    build:
      #dockerfile: /root/Dockerfile
      path: "/root/nifi/files"

- name: REMOVE FILE
  ansible.builtin.file:
    path: "/root/nifi/files"
    state: absent

- name: RUN
  docker_container:
    name: nifi
    image: nifi-pbl:1.0.0
    ports:            
      - "8080:8080"   
    detach: true
    restart_policy: always