---
# Playbook principal
- name: Actualizar sistema e instalar Docker
  hosts: debian-vm  # Ejecutar en el grupo 'googlecloud'
  become: yes  # Utilizar privilegio de superusuario
  roles:
    - system_upgrade  # Ejecutar el rol para actualizar el sistema
    - install_docker  # Ejecutar el rol para instalar Docker
