
- name: COPY FILES
  copy:
    src: "{{ role_path }}/files"
    dest: /home/user/


- name: BUILD IMAGE
  community.docker.docker_image:
    name: kafka:latest
    source: build
    build:
      #dockerfile: /root/python3/Dockerfile
      path: /home/user/files

- name: RUN zookeeper
  docker_container:
    name: zookeeper
    image: zookeeper:3.9.2-jre-17
    state: started
    ports:
      - "2181:2181"
    #restart_policy: always
    detach: yes

- name: RUN kafka
  docker_container:
    name: kafka
    image: kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "/home/user/kafka_volume:/opt/kafka/data" 
    detach: true
